<?php  $bookmark = $_GET["bookmark"];  ?>

	<p>
	<input type="button" value="1.上傳成績 (EXCEL檔)" 
		class="btn <?php echo ( $_GET["bookmark"]=="uploadexcel")?"btn-info":"btn-default"; ?> btn-lg" 
		onclick="location.href='<?php echo $this->baseUrl($this->module.'/'.$this->controller.'/'.$this->action.'?bookmark=uploadexcel');?>'">
	<i class="fa fa-arrow-right fa-2x" aria-hidden="true"></i>
	<input type="button" value="2.上傳圖片 (壓縮檔)" 
		class="btn <?php echo ( $_GET["bookmark"]=="uploadimage")?"btn-info":"btn-default"; ?> btn-lg" 
		onclick="location.href='<?php echo $this->baseUrl($this->module.'/'.$this->controller.'/'.$this->action.'?bookmark=uploadimage');?>'">
	<i class="fa fa-arrow-right fa-2x" aria-hidden="true"></i>
	<input type="button" value="3.完成" 
		class="btn <?php echo ( $_GET["bookmark"]=="finish")?"btn-info":"btn-default"; ?> btn-lg" 
		onclick="location.href='<?php echo $this->baseUrl($this->module.'/'.$this->controller.'/'.$this->action.'?bookmark=finish');?>'">

	</p>


<div class="row">
	<div class="col-md-8">	
		<?php if (isset($this->message)){ ?>
		<div class="alert alert-danger alert-dismissible fade in" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<?php echo $this->message;?>
		</div>
		<?php } if($bookmark=='uploadexcel'){ ?>
		<div class="alert alert-info" >
			<form method='post'
				class="form-horizontal"
				action="<?php echo $this->baseUrl($this->module.'/'.$this->controller.'/'.$this->action.'?bookmark=uploadimage');?>" 
				enctype="multipart/form-data">
				<input id='myksuid' type='hidden' name='myksuid' />
				<input id='mystuid' type='hidden' name='mystuid' />
				<input id='mytcode' type='hidden' name='mytcode' />
				<input id='mycreated' type='hidden' name='mycreated' />
				<input id='myinformation' type='hidden' name='myinformation' />
				<input id='myprogram' type='hidden' name='myprogram' />		
				<input id='mycername' type='hidden' name='mycername' />		
				<input id='mycomment' type='hidden' name='mycomment' />	
				<input id='mydepartment' type='hidden' name='mydepartment' />	
				<input id='myusdepartment' type='hidden' name='myusdepartment' />	
				
				<div class="form-group">
					<label class="col-sm-2 control-label">證照名稱</label>
					<div class="col-sm-10">
						<select id="mycategory" class="form-control" name="mycategory">		
							<option value="">請選擇</option>
							<option value="BULATS">BULATS</option>
							<option value="GET">GET</option>
							<option value="CSEPT">CSEPT</option>
							<option value="NETPAW">NETPAW</option>
							<option value="TOEIC">TOEIC</option>
						</select>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">選擇檔案</label>
					<div class="col-sm-10">
					<input id="filename" class="" type="file" name="loadExcel">
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">認證日期</label>
					
					<div class="col-sm-10">
						<input id="myissue" class="form-control" type="text" name="myissue"/>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
					<input id="uploaded" name="action" type="submit" class="btn btn-info" value="上傳成績" />	
					</div>
				</div>	
			</form>
		</div>	
		<?php }else if($bookmark=='uploadimage'){ ?>
		<div class="alert alert-info" >
			<!-- 上傳多張圖片 -->
			<form class="form-horizontal" method="post"	action="<?php echo $this->baseUrl($this->module.'/'.$this->controller.'/'.$this->action);?>" enctype="multipart/form-data">
				<div class="form-group">
					<label for="inputEmail3" class="col-xs-4 col-sm-2 control-label">選擇圖片</label>
					<div class="col-xs-12 col-sm-5">
						<input type="file" name="files[]" multiple="" />
					</div>
					<div class="col-xs-12 col-sm-5">
						<input name="action" type="submit" class="btn btn-info" value="上傳images" />
					</div>
				</div>
			</form>
			<!-- 上傳多張圖片 -->	
		</div>
		<?php }else if($bookmark=='finish'){ ?>
		<div class="alert alert-info" >
			<p>恭喜您終於完成了 ;)</p>
		</div>
		<?php } ?>


	</div>
	


<?php  if (isset($this->image)){ ?>
		<div class="alert alert-warning alert-dismissible fade in" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<div class="row">
				<p><?php echo $this->image;?></p>
			</div>
		</div>
<?php } ?>

<script type="text/javascript">	
	$('#myissue').datepicker({
		dateFormat: "yy-mm-dd"
	});
</script>



