

	<p>
		<button type="button" class="btn btn-default btn-lg">1.上傳成績 (EXCEL檔)</button>
		<i class="fa fa-arrow-right fa-2x" aria-hidden="true"></i>
		<button type="button" class="btn btn-default btn-lg">2.上傳圖片 (壓縮檔)</button>
		<i class="fa fa-arrow-right fa-2x" aria-hidden="true"></i>
		<button type="button" class="btn btn-default btn-lg">3.完成</button>
	</p>


<div class="alert alert-success">

</div>





<div class="alert alert-danger alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <?php echo $this->message;?>
  哈囉


  <div class="row">
  	<div class="col-md-4">
		<img src='/ccawww/public/upload/english/temp/S102000606-4020Y043-7020.jpg' class='img-thumbnail'>
		<p>4010Q022</p>
	</div>
	<div class="col-md-4">
		<img src='/ccawww/public/upload/english/temp/S102000606-4020Y043-7020.jpg' class='img-thumbnail'>
	 	<p>4010Q022</p>
	</div>
	<div class="col-md-4">
		<img src='/ccawww/public/upload/english/temp/S102000606-4020Y043-7020.jpg' class='img-thumbnail'>
		<p>4010Q022</p>
	</div>
  </div>













</div>






